### ISSUE TITLE
Python binding

### ISSUE THREAD

**Issue by smeng9** [frankaemika/libfranka#101]
Is anyone in the community interested in getting a python binding for the library?
The python binding will need to include all the header files from include/franka folder and bind with pybind11

Seems now the only way to use python is through ros, which is not a direct communication with the robot.

**Comment by AndreasKuhner** [comment]
Hi @smeng9 ,
I think nowadays a few python binding already exists. I don't want to promote one or the other but a quick google search yields good results :smile: 

Cheers,
Andreas
