### ISSUE TITLE
Standard input stream overloading

### ISSUE THREAD

**Issue by arsh09** [frankaemika/libfranka#104]
Hello, 

I am trying a teleoperation network for a leader/follower scenario using two Panda robots where I am sending leader robot states to follower and follower robot states to leader using asynchronous UDP network (using Boot Asio) running in a completely different thread.

I am facing the issue in the overloading method. As I understand, RobotState can be converted into a output stream using this [RobotState output stream overloading function](https://github.com/frankaemika/libfranka/blob/master/include/franka/robot_state.h#L381)

However, when it is received on the other end, there seems to be no input stream overloading method. Is there any way I can convert it back from bytes array to RobotState struct? 

I have tried to parse the string as well as use a JSON library but both are not very good solutions. 

I realise that [franka_ros ](https://github.com/frankaemika/franka_ros) must be doing something similar for FrankaJointState and FrankaRobotState controllers, if someone can point me in the direction, it will be a great help.

Thank you

**Comment by AndreasKuhner** [comment]
Hi @arsh09 ,
might be a bit of a late answer... 

For ROS 2 we 'stream' the robot state to our franka robot state publisher as... well, pointer and re-interpret it as struct on the other side. This has a lot to do with how the ros2_control framework is designed...

Will will have a look if as future feature it might make sense to have additional functionality around libfranka providing some sort of  forwarding but if it is no problem, then ROS 2 is a great solution :grinning: 

Cheers,
Andreas

P.S. If you have further input, don't hesitate!
