### ISSUE TITLE
Add a custom coordinate frame

### ISSUE THREAD

**Issue by thume4zzzz** [frankaemika/libfranka#106]
Hi, I want to fulfill the function of Remote Center of Motion (RCM), and design an impedance controller to control the translation of the virtual point (3DOF) and the translation of the TCP simultaneously. 
Is it possible to add a virtual frame so that I can directly call ZeroJacobian() or BodyJacobian()? Are there any examples for reference？

**Comment by AndreasKuhner** [comment]
Hey @thume4zzzz ,
if it is still relevant... there is nothing out-of-the box from our side. I guess, you would need to implement your own functionality around the existing parts. But of course, if you have further input, we would be happy to hear about it - everything we know, we can consider in upcoming feature :)

Cheers,
Andreas
