### ISSUE TITLE
Grasp failed when grasp() is called consecutively

### ISSUE THREAD

**Issue by fengzileee** [frankaemika/libfranka#108]
Hi,

I'm attempting to use the [grasp method](https://frankaemika.github.io/libfranka/classfranka_1_1Gripper.html#abff6a03a6c75b9079bd4b9b5ca380254) of the `Gripper` to adjust the grasp force in the following manner:

```c++
bool success = gripper.grasp(width, 15);  // grasp with 15N, will return true
bool success = gripper.grasp(width, 13);  // try to grasp with 13N, will always return false
```

However, it seems that the grasp will be automatically considered failed if the gripper is already grasping something. Is this the intended behavior?

Thanks!

**Comment by AndreasKuhner** [comment]
Hi @fengzileee ,
I hope you could nonetheless complete your task :)

We know that we didn't advance on the gripper for quite some time. So, if you have any further input, please don't hesitate to share. Everything we can get, we then also can use for further generations of grippers!

Cheers,
Andreas
