### ISSUE TITLE
Is it possible to get Coriolis Matrix C(q,dq) from model handle directly?

### ISSUE THREAD

**Issue by thume4zzzz** [frankaemika/libfranka#115]
I'm trying to realize collision detection myself and the term C^T * dq is required.
However, the model handle getCoriolis can only return Coriolis force, but not Coriolis matrix C.

Of course, I can calculate  C^T * dq by  C^T * dq =\dot{M} * dq - Coriolis force, but is there more direct way to get it?

**Comment by AndreasKuhner** [comment]
Hi @thume4zzzz ,
I guess your proposed version is for now the directest way ... :)

Cheers,
Andreas
