### ISSUE TITLE
Error building libfranka using VS2019 and VS2017 as well

### ISSUE THREAD

**Issue by avadhutmali999** [frankaemika/libfranka#121]
**Installed vcpkg, poco and eigen 3 as mentioned in documentation.
Later started building the project using VS by opening the CMakelist.txt as mentioned in documentation.
Getting the error as pasted below**

CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message): Could NOT find Poco (missing: Poco_INCLUDE_DIR Poco_LIBRARIES Net Foundation)		

Also tried providing the poco directory paths manually but to no avail , its not helpful.
Please guide on mistakes if any / solution to the issue.

**Comment by fcc315** [comment]
I installed vcpkg, and then use vcpkg to install poco:x64-windows. After then I build libfranka using this command: 

```cmd
cmake -DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake ..
```
Poco will be found located correctly.
