### ISSUE TITLE
libfranka: Move command rejected: command not possible in the current mode ("User stopped")!

### ISSUE THREAD

**Issue by BolunDai0216** [frankaemika/libfranka#128]
Hi,

I was trying to run the libfranka example `communication_test`, but I got the following error

```console
libfranka: Move command rejected: command not possible in the current mode ("User stopped")!
```

Can anyone help me understand how I can change the `robot_mode`?

Thanks in advance!

I did check the IP address of the robot, and the emergency stop is not pressed. The robot is flashing green lights. I also tried restarting the terminal and it did not work.

**Comment by BolunDai0216** [comment]
> Hi,
> 
> I was trying to run the libfranka example `communication_test`, but I got the following error
> 
> ```
> libfranka: Move command rejected: command not possible in the current mode ("User stopped")!
> ```
> 
> Can anyone help me understand how I can change the `robot_mode`?
> 
> Thanks in advance!
> 
> I did check the IP address of the robot, and the emergency stop is not pressed. The robot is flashing green lights. I also tried restarting the terminal and it did not work.

The issue was I did not disable the safety rules in watchman.

**Comment by blackholebug** [comment]
To disable the safety rules, you need: 1). a safety operator account; 2). delete all the rules in the watchman under the Work Scenario; 3). test your code in the Execution Mode (System status shows ready now).  Thanks to @BolunDai0216 for sharing the hints!

**Comment by andrejpan** [comment]
This discussion [thread](https://www.franka-community.de/t/libfranka-move-command-rejected-command-not-possible-in-the-current-mode-user-stopped/4454/10?u=andrejpan) should also be helpful on this topic.
