### ISSUE TITLE
Opening Brakes Failed

### ISSUE THREAD

**Issue by homangab** [frankaemika/libfranka#140]
Hi, When I click on "Unlock Joints" from the Franka dashboard (robot is yellow), it displays an error message "Opening Brakes Failed" and does not turn blue - this happened suddenly, and the robot has been working fine prior to this. Could you kindly advise on potential fixes? (i tried turning off and on again several times, and also made sure the stop or brakes are non on)

Thanks!
-- Homanga

![opening_brakes_failed](https://github.com/frankaemika/libfranka/assets/28483305/a4b4db9f-f7c9-49fa-b30a-b8f0a3c011db)

**Comment by davidschnermann** [comment]
Hi Homanga,

we have the same problem now. How did you fixed it?

Thanks.

David

**Comment by AndreasKuhner** [comment]
Hi @homangab and @davidschnermann ,
I guess for this error, the best contact point is [support@franka.de](mailto:support@franka.de).

If anything further is open, don't hesitate to open a new issue :robot:
