### ISSUE TITLE
libfranka 0.11.0 

### ISSUE THREAD

**Issue by saivojjala** [frankaemika/libfranka#141]
Hi, I was recently attempting to build franka_ros2 for ros2 humble. However the package franka_hardware requires libfranka version 0.11.0. I tried using a different version 0.9.2 and 0.10.0 but the build threw an error as those version seem to be missing the active_control.h header file. 

Please look into this, I have raised an issue in franka ros2 repository as well, but no response yet.

**Comment by BarisYazici** [comment]
For latest franka_ros2 [V0.1.3](https://github.com/frankaemika/franka_ros2/releases/tag/v0.1.3) you need the fr3-develop branch from the libfranka repository which is the v0.11.0.

**Comment by BarisYazici** [comment]
You can use an earlier franka_ros2 version v0.1.0 which works with libfranka v0.10.0

**Comment by saivojjala** [comment]
okay thank you, it built successfuly now
