### ISSUE TITLE
error: debian/rules build subprocess returned exit status 2

### ISSUE THREAD

**Issue by addy1997** [frankaemika/libfranka#149]
Hi there,

I am trying to install the real-time kernel on Ubuntu 20.04. My Kernel version is `5.15.0-67-generic` and I'm trying to install 5.9.1 following exactly all the instructions from the franka documentation page. 

I get this error after running `make -j$(nproc) deb-pkg` command.

```
make[2]: *** [debian/rules:6: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:77: deb-pkg] Error 2
make: *** [Makefile:1523: deb-pkg] Error 2
```
Please can anybody suggest a solution?

**Comment by AricLau07** [comment]
hi! how did u slove this ? thanks for any help!
