### ISSUE TITLE
examples fail

### ISSUE THREAD

**Issue by MassaRoddel** [frankaemika/libfranka#15]
if i try to run the examples - most of them fail with either:

libfranka: Cannot load model library: Cannot load library

or messages like:

libfranka: Move command aborted: motion aborted by reflex! ["joint_motion_generator_velocity_discontinuity"]
control_command_success_rate: 0.16

Only echo_robot_state works.
What could be the reason for these problems?
Update 1.2 was installed on the robot.

How do I get the current cartesian coordinates of the tool center point?

Thx

**Comment by MassaRoddel** [comment]
Is the address model the problem? The source code suggests that there is support only for x64?

**Comment by fwalch** [comment]
Yes, the model library currently only supports x64. We'll update the documentation to point that out.

The low control command success rate indicates that the commands don't arrive at the robot in time. If you are not on x64, possibly your hardware doesn't provide enough performance. You can also try the steps outlined in https://frankaemika.github.io/docs/troubleshooting.html#motion-stopped-due-to-discontinuities-or-communication-constraints-violation.

**Comment by MassaRoddel** [comment]
64Bit OS fixed the load library problem and a better patch cable fixed the timing problem.
Thanks
