### ISSUE TITLE
Version Incompatibility

### ISSUE THREAD

**Issue by mahdichalaki** [frankaemika/libfranka#158]
I've installed the latest version of libfranka (13.3) on my PC with Ubunto 22.04, and the latest System version (5.6.0) on the FR3 robot. I'm using ROS2 Humble, and when trying to run the MoveIt example ("ros2 launch franka_moveit_config moveit.launch.py robot_ip:=<fci-ip>"), I get an error stating:

"[FrankaHardwareInterface]: libfranka: Incompatible library version (server version: 7, library version: 8). Please check https://frankaemika.github.io for Panda system updates or choose a libfranka version that uses the server version 7 from the table at https://frankaemika.github.io/docs/compatibility.html ."

I'm not sure if these versions are compatible, and what does version 7 and 8 mean here.

**Comment by af-a** [comment]
Hi @mahdichalaki.

I am not a maintainer, but I ran into the same issue and the following might help. 

If you are installing `libfranka` from source, make sure you run `git submodule update` after checking out the tag of the specific version that you are building. I also have FR3 5.6.0 +  Ubuntu 22.04 and `libfranka` `0.13.3` works fine.

This step seems to have been omitted from the `franka_ros2` [setup instructions](https://support.franka.de/docs/franka_ros2.html#prerequisites).
