### ISSUE TITLE
communication_constraints_violation after update

### ISSUE THREAD

**Issue by MassaRoddel** [frankaemika/libfranka#20]
After updating firmware to 1.3.2 and libfranka to 0.5.0 I always get communication_constraints_violation errors. The example communication_test fails too.
The ping test results are no different from before the update.
My code always fails with the same value of 0.78 now. Do we need more cpu power for version 0.5.0 than 0.3.0? Could this be the problem?

**Comment by jrmout** [comment]
There should be no difference. Maybe you forgot to compile in Release mode ( cmake -.DCMAKE_BUILD_TYPE=Release .. )?

**Comment by jrmout** [comment]
If you don't specify the CMAKE_BUILD_TYPE variable then it will be empty and no additional flags will be set.

**Comment by MassaRoddel** [comment]
Now communication works but the code to move to cartesian coordinates does not. The robot still moves but much less distance and without errors.
ie  robot should move 100mm but it moves only 4mm.
Any ideas what the problem could be?

**Comment by jrmout** [comment]
The last release added lowpass filters on libfranka side. As you edited, deactivating those should help.
