### ISSUE TITLE
cartesian_velocity_violation

### ISSUE THREAD

**Issue by Oeser** [frankaemika/libfranka#22]
I'm running consistently into a cartesian_velocity_violation. Is there any (safe) way to increase or bypass this limit?

**Comment by sgabl** [comment]
Hi, these limits are hardware limits and can't be increased. You'll find more information [here](https://frankaemika.github.io/docs/control_parameters.html) and [here](https://frankaemika.github.io/docs/libfranka.html#errors). Please check your connection as well with the `communication test` example.
