### ISSUE TITLE
swapped orientation of the F_ext force components?

### ISSUE THREAD

**Issue by christgau** [frankaemika/libfranka#26]
According to the messages of the `/franka_state_controller/F_ext` topic the force is given with respect to the panda_K frame. Now assume that the robot is positioned such that the z-axis of the K frame points downwards in direction of gravity (check by using rviz). If one pulls the gripper downwards, i.e. in direction of gravity, the force's z component in the F_ext messages increases in negative direction although the z-axis points in the same direction of the acting force. Identical behavior is observed for forces in the other directions.

Is this intended behavior? So do the values in F_ext represent the counterforce of the actual acting force? In other words: are the signs/orientations of the force componenents swapped by intention?

A short notice on that and may be a hint in the documentation would be really great.

**Comment by AndreasKuhner** [comment]
If you encounter any other issue, please re-open the issue again. Thanks to everybody! :smile:
