### ISSUE TITLE
How to change the communication to UDP

### ISSUE THREAD

**Issue by gmezzina23** [frankaemika/libfranka#30]
Dear all,

I already communicate via main pc ----> robot, through TCP/IP protocol (normal use), but at the moment I need to communicate "in parallel" with robot ---> another pc by using an UDP protocol.
Someone can briefly explain me the procedure to do this?

I'm completely newbie in this field.

Thanks.

**Comment by sgabl** [comment]
Hi,

when using libfranka, the robot will establish a connection through TCP. However, the real-time control is done through a UDP channel.
I think what you want is to have a second PC reading the robot state? It is not possible to have two simultaneous connections to the robot. You could forward the robot state from your PC to the second PC or use franka_ros and use the published ROS topics.

**Comment by gmezzina23** [comment]
Dear sgabl,

thank you for the answer. So I change my question,  is it possible to set an UDP communication between the main pc and the robot?
In which way I can do it?

Thank you ,
