### ISSUE TITLE
cartesian position control

### ISSUE THREAD

**Issue by Gathiyo** [frankaemika/libfranka#34]
Here, [https://frankaemika.github.io/docs/libfranka.html#realtime-commands](url) it says that motion generator can be for Cartesian coordinates also, but from here, [https://frankaemika.github.io/libfranka/classMotionGenerator.html](url) it seems that this is only for joint space angles, can you please specify is it possible to do motion generation in Cartesian coordinates.

**Comment by fwalch** [comment]
As the docu says, the `MotionGenerator` class is only an example. See https://frankaemika.github.io/libfranka/examples.html (or directly in source code) for more examples (`generate_*`) using all four motion generator interfaces.
