### ISSUE TITLE
convert between cartesian and joint space cordinate 

### ISSUE THREAD

**Issue by Gathiyo** [frankaemika/libfranka#35]
How can I convert between Cartesian and joint space coordinate, is there a function that I can use directly for this conversion?

**Comment by fwalch** [comment]
This is called inverse kinematics. We currently don't provide a library for that. See also https://github.com/frankaemika/libfranka/issues/24. For the other direction (forward kinematics), you can use the [model library](https://frankaemika.github.io/libfranka/classfranka_1_1Model.html).
