### ISSUE TITLE
Recovery from errors

### ISSUE THREAD

**Issue by LR86** [frankaemika/libfranka#37]
Hi all,

I'm using libfranka to program my application in c++ and I would like to understand if there's a way to recover from errors.
I saw that in ROS there's an error recovery action. Unfortunately at the moment I cannot use ROS.

Any suggestion?

Loris

**Comment by LR86** [comment]
Ok, probably it is just robot.automaticErrorRecovery();
Am I right?

Loris

**Comment by fwalch** [comment]
Yes, libfranka's `Robot::automaticErrorRecovery` is the same as the ROS error recovery action.
