### ISSUE TITLE
libfranka: UDP receive: Timeout

### ISSUE THREAD

**Issue by PioBeat** [frankaemika/libfranka#40]
Hello!

I noticed some problems when using libfranka. Whenever I try to connect to Panda I get the following error:
`libfranka: UDP receive: Timeout`.
This happens with all of the examples scripts within the library, for example, https://frankaemika.github.io/libfranka/print_joint_poses_8cpp-example.html and even if I try to compile them by myself. This simple line fails: `franka::Robot robot("172.31.1.51");`

My setup is as follows:

_My workstation_
- Ubuntu 18.04.2 LTS
- Kernel: Linux iosensedg 4.14.12-rt10 #1 SMP PREEMPT RT Wed Apr 24 11:30:58 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
- Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 10)
- libfranka version: 0.6.0

_Panda_
- System version: 2.1.1 (ced048bda3)

I am directly connected to the Panda. What might be the reason? 

The simple ping test gave me this:
```
--- 172.31.1.51 ping statistics ---
10000 packets transmitted, 10000 received, 0% packet loss, time 10079ms
rtt min/avg/max/mdev = 0.715/0.937/1.083/0.042 ms
```

**Comment by sgabl** [comment]
Hi,

I assume, that the `FCI Feature` is missing on your robot. Please have a look at `Settings -> System` and check `Installed Features`. If this is the case, please install the feature or contact support@franka.de resp. your distributor.

Further, your ping results are far too high for a 1kHz control loop. I assume you should replace your Realtek Ethernet Controller with a good Intel Server NIC (e.g. Intel I350 V2) to get an average ping below 0.2 ms.
