### ISSUE TITLE
Force reads force

### ISSUE THREAD

**Issue by Junhyuck-Woo** [frankaemika/libfranka#42]
I tried to read a force from the end-effector.
However, I couldn't find any example codes.
So, I have two questions.
1. Can I read a force data from the gripper?
2. Is there any gripper-force reading code?

I will be waiting a your response.
Thank you.

**Comment by sgabl** [comment]
Hi,

there is no feedback of the measured grasping force in the GripperState. Have a look at the [GripperState](https://github.com/frankaemika/libfranka/blob/master/include/franka/gripper_state.h) to see the data we provide. If you want to know the external force / torque in the gripper frame have a look at the `K_F_ext_hat_K` of the [RobotState](https://github.com/frankaemika/libfranka/blob/master/include/franka/robot_state.h).
