### ISSUE TITLE
libfranka on Windows 10

### ISSUE THREAD

**Issue by MarcelBa** [frankaemika/libfranka#43]
Hello,

I try to run the "echo-robot-state"-example on a windows 10 PC. I downloaded libfranka-library, libfranka-common, the latest eigen-library and poco1.9.0. I'm able to compile the example in visual studio without getting an error message. But when I try to run the example I get the "UDP receive: Timeout"-message. 
- ping-check is ok
- robot controller is directly connected to the pc
- FCI is installed
Same example works fine on the same PC running Ubuntu. If you need more detailed informations, tell me.

Thank you.
MarcelBa

**Comment by fwalch** [comment]
Does turning off the Windows firewall help?

**Comment by MarcelBa** [comment]
Hello fwalch,

thanks for your answer. That was too easy 😆 now it works. Thank you!

**Comment by fwalch** [comment]
You're welcome!
