### ISSUE TITLE
Camera-on-hand not accounted for when running examples

### ISSUE THREAD

**Issue by aPonza** [frankaemika/libfranka#48]
I've mounted a hand camera between flange and hand and I can't run examples without eventually running into a reflex state due to (I think) the controller not accounting for the extra weight. I can e.g. run
```
$ cd libfranka/build
$ ./examples/communication_test <robot_ip>
```
and I see the arm moving to the home position, then performing the test while the "forearm" falls towards the base. The test ends in self collision (without of course the robot actually physically touching itself).

**Comment by fwalch** [comment]
If you have a fixed additional weight mounted to the flange/end-effector, you should configure this in Desk in Settings -> End-Effector.

For a dynamic payload, see [`franka::Robot::setLoad`](https://frankaemika.github.io/libfranka/classfranka_1_1Robot.html#afcb708df10f24563dbcf7d5b907b4a15).

**Comment by aPonza** [comment]
Cheers, thank you.
