### ISSUE TITLE
Robot doesn't move

### ISSUE THREAD

**Issue by XiaoxiaoZ** [frankaemika/libfranka#6]
Hi, Franka team
I am trying to setup the robot with libfranka. The desk from web browser works fine but when I want to run libfranka, it doesn't move. I am able to echo robot state but for instance if I run 
·/joint_impedance_control 192.168.0.131 0.2 0.5 10 
The robot should draw a circle right? But it was not moving, I can hear the voice from the robot the same as I pressed the pilot gray buttons. If I try to run the example from tutorial, 
./generate_joint_velocity_motion 192.168.0.131
Nothing happened, not even the sound.
Please help.

**Comment by hamid5746** [comment]
Please send an email to support@franka.de for issues that are not directly related to the code.
