### ISSUE TITLE
Other way to unlock joints than from desk

### ISSUE THREAD

**Issue by liborw** [frankaemika/libfranka#63]
Is it possible to unlock joints programmatically?

**Comment by Hymwgk** [comment]
Same question

**Comment by Hymwgk** [comment]
Hi, I got this ,but I haven't try it yet
[https://github.com/ib101/DVK/blob/master/Code/DVK.py](url)

**Comment by eugenegalaxy** [comment]
> Hi, I got this ,but I haven't try it yet
> [https://github.com/ib101/DVK/blob/master/Code/DVK.py](url)

Hey, I have tried this code (unmodified) and it worked! Using Python 3.6, Ubuntu 18.04.

**Comment by jk-ethz** [comment]
My solution to this
https://github.com/jk-ethz/franka-lock-unlock

**Comment by AndreasKuhner** [comment]
Hi all,
while not providing an official way of locking/unlocking joints, there seems to be workarounds... :)

Cheers,
Andreas

P.S. If you have further input, please open another issue.
