### ISSUE TITLE
can't use libfranka with add_subdirectory in cmake

### ISSUE THREAD

**Issue by Pascal-So** [frankaemika/libfranka#67]
When I add libfranka as a git submodule to my own cmake project and use `add_submodule`, the cmake configure step fails with `Could not find a package configuration file provided by "Poco"`.

The reason for this is on line 7 in CMakeLists.txt:
```cmake
list(INSERT CMAKE_MODULE_PATH 0 ${CMAKE_SOURCE_DIR}/cmake)
```

`CMAKE_SOURCE_DIR` points to the source directory of my own cmake project, not to the root of libfranka, therefore your FindPoco.cmake is not found. The fix for this is simple, the path should start at `CMAKE_CURRENT_LIST_DIR`.

Is there a specific reason that `CMAKE_SOURCE_DIR` was chosen that I'm not seeing here? If not I'll be happy to send a PR.

**Comment by sgabl** [comment]
In general we recommend including libfranka in your project like the [following](https://frankaemika.github.io/docs/faq.html#how-can-i-use-libfranka-in-my-own-cmake-based-project)

Sounds good, looking forward to your PR!
