### ISSUE TITLE
Missing feature: Inverse Kinematics

### ISSUE THREAD

**Issue by fbottarel** [frankaemika/libfranka#69]
Greetings everyone. I recently started looking into using `libfranka` in control loops and I thought I would have been able to find a method to obtain the inverse kinematics from the `franka::Model` class.

As far as I can understand, the IK is computed anyway within the FCU when a cartesian trajectory is commanded. What is the recommended way of solving the IK for any workspace pose without the need to install third-party libraries?

Not being able to query the FCU for a IK computation seems like a weird oversight, maybe there is a very reasonable explanation though.

**Comment by AndreasKuhner** [comment]
Hi @fbottarel ,
if you are still interested, then we followed a slightly different route... in a ROS environment, there is plenty of 3rd party software which can give you a whole plethora of IKs. We also provide an example in ROS 2 which could be used as a start point: https://github.com/frankaemika/franka_ros2/blob/humble/franka_example_controllers/src/joint_impedance_with_ik_example_controller.cpp

Cheers,
Andreas
