### ISSUE TITLE
Accuracy in cartesian space and units

### ISSUE THREAD

**Issue by publicDaniel** [frankaemika/libfranka#72]
Hey guys! Currently I'm using your panda-arm in conjunction with ROS-Kinetic and MoveIt! - pathplanning with collision detection and execution works fine. 
## Inaccuracies in cartesian space
I started testing more with the robot and detected inaccuracies as I moved the robot in cartesian space. For instance, when I tell MoveIt! to move the robot e.g. <img src="https://render.githubusercontent.com/render/math?math=1 \ mm"> up in Z-direction, the robot just doesn't move that <img src="https://render.githubusercontent.com/render/math?math=1 \ mm"> up respecting the spezified tolerance of <img src="https://render.githubusercontent.com/render/math?math=0.1 \ mm">. John-HarringtonNZ seems to have a similar issue as he states in #53 "Calibrated DH Parameters". 
## Units
Some other questions rised as I tested different parameters for the collision thresholds, cartesian- and joint impedances.

You documented very nicely the units and borders of the cartesian impedance parameters. 
Coordinate impedances are given in the unit <img src="https://render.githubusercontent.com/render/math?math=\left[ \frac{N}{m} \right ]"> - orientational impedances in the unit <img src="https://render.githubusercontent.com/render/math?math=\left[ \frac{Nm}{rad} \right ]">. Seems clear to me although different cartesian impedances do not affect the behavior of the robot. 
I'm wondering about the unit for the joint impedances. I estimate the joint impedances are - like the cartesian orientational impedances - given in the unit <img src="https://render.githubusercontent.com/render/math?math=\left[ \frac{Nm}{rad} \right ]">. Is that right? Regarding the borders of the joint impedances - is the maximum value for joint impedances <img src="https://render.githubusercontent.com/render/math?math=14250"><img src="https://render.githubusercontent.com/render/math?math=\frac{Nm}{rad}">? Higher values are not accepted by the FCI. Altering the joint impedances do indeed affect the behavior of the robot. 

As you state in the documentation the parameters for the cartesian orientation collision thresholds (_Roll_, _Pitch_, _Yaw_) are given in the unit <img src="https://render.githubusercontent.com/render/math?math=\left [ N \right ]">. It's not clear to me, why these values are not given in the unit <img src="https://render.githubusercontent.com/render/math?math=\left [ Nm \right ]">.  
During my testing I recognised that lower values than <img src="https://render.githubusercontent.com/render/math?math=10N"> for the cartesian- and  <img src="https://render.githubusercontent.com/render/math?math=10Nm"> for the joint collision thresholds seem to have no effect on the robot. Are there also borders like there are with the impedance values in cartesian space?

Kind regards, 
Daniel

**Comment by AndreasKuhner** [comment]
If there is still an open question, please don't hesitate to re-open the ticket.
