### ISSUE TITLE
more verbose error messages

### ISSUE THREAD

**Issue by ndehio** [frankaemika/libfranka#73]
Is it possible to get more verbose error messages from libfranka?

For example, I receive this message
`():  libfranka: Move command aborted: motion aborted by reflex! ["self_collision_avoidance_violation"]`
and I would like to know exactly which two links are to close to each other.

Thanks for your support.
Niels

**Comment by AndreasKuhner** [comment]
Hi @ndehio ,
thank you for your input. Yes, we also think that libfranka can do better... and have it on our internal road map! Of course that needs also some refactoring in the backend. Meaning... it takes a while...

If you have further input, don't hesitate to throw it at us :grinning: 

Cheers,
Andreas
