### ISSUE TITLE
Feature Request: setSelfCollisionBehavior()

### ISSUE THREAD

**Issue by ndehio** [frankaemika/libfranka#74]
We can already set thresholds for joint/cartesian collisions via the `setCollisionBehavior()` function.
Could you please also provide a method to modify the thresholds for self-collisions?
Thanks

**Comment by Stakkay** [comment]
The [setCollisionBehavior()](https://frankaemika.github.io/libfranka/classfranka_1_1Robot.html#a168e1214ac36d74ac64f894332b84534) function let's the user set force and torque thresholds to detect contacts and collisions. Self-collisions on the other hand happen when the geometry of the robot intersects with itself (i.e. one part of the robot gets too close to another part of the robot). What thresholds do you want to set for self-collisions?

**Comment by AndreasKuhner** [comment]
Hi @ndehio 
as @Stakkay mentioned, setting thresholds for self-collisions (aka the robot hits itself), is more like a thing of 'please don't do'. Hence, the collision volumes are chosen to prevent any self-harm (and not configurable).

Cheers,
Andreas
