### ISSUE TITLE
Update ROS package repository with v0.8.0

### ISSUE THREAD

**Issue by simonbogh** [frankaemika/libfranka#75]
Hi,

Will `ros-melodic-libfranka` be updated to the latest version 0.8.0?

**Comment by sgabl** [comment]
Hi,

PR is [merged](https://github.com/ros/rosdistro/pull/25632), so the package should soon (1-3 weeks) be available.

**Comment by simonbogh** [comment]
Hi @sgabl 

Great, looking forward to it. Thanks for the quick reply.
