### ISSUE TITLE
libfranka: Move command aborted: motion aborted by reflex! ["cartesian_motion_generator_joint_acceleration_discontinuity"] 

### ISSUE THREAD

**Issue by Africaggy** [frankaemika/libfranka#78]
when I have download libfranka,I use "cmake.."and"make"in libfranka/example. Then I got some executable files, I run some files perfect.But I run "generate_cartesian_pose_motion"wrong,apppeared the above probelm. Have anyone this problem?Or have anyone can solve problem and have a new pose_motion

**Comment by Africaggy** [comment]
I have solved it.Thanks guys

**Comment by michtesar** [comment]
Hey @Africaggy how did you solved it?
This is what I get when I send joints states. After some I get the same error:
```
libfranka: Move command aborted: motion aborted by reflex! ["cartesian_motion_generator_joint_acceleration_discontinuity"]
```

**Comment by whyy812** [comment]
Hey, @Africaggy 
We are struggling with the similar issues, too. Now that you have  solved the similar issues, could you please share the solutions ?
Best regards.

**Comment by Africaggy** [comment]
I think you can smooth its motion。But you need use&nbsp;Quintic spline fitting



发自我的iPhone


------------------ Original ------------------
From: whyy ***@***.***&gt;
Date: Mon,Jul 5,2021 9:15 PM
To: frankaemika/libfranka ***@***.***&gt;
Cc: Africaggy ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [frankaemika/libfranka] libfranka: Move command aborted: motion aborted by reflex! ["cartesian_motion_generator_joint_acceleration_discontinuity"]  (#78)





 
Hey, @Africaggy
 We are struggling with the similar issues, too. Now that you have  solved the similar issues, could you please share the solutions ?
 Best regards.

**Comment by whyy812** [comment]
I will try. Thank you @Africaggy.

**Comment by Africaggy** [comment]
You are welcome



发自我的iPhone


------------------ Original ------------------
From: whyy ***@***.***&gt;
Date: Mon,Jul 5,2021 10:13 PM
To: frankaemika/libfranka ***@***.***&gt;
Cc: Africaggy ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [frankaemika/libfranka] libfranka: Move command aborted: motion aborted by reflex! ["cartesian_motion_generator_joint_acceleration_discontinuity"]  (#78)





 
I will try. Thank you @Africaggy.

**Comment by undefinedcodezhong** [comment]
Hello, I want to know if there is an instruction or function to recover the movable state by code way when the robot is in the reflex state.
Anyone can help?  Thanks.

**Comment by marcbone** [comment]
You can use the [automaticErrorRecovery](https://github.com/frankaemika/libfranka/blob/f3b8d775a9c847cab32684c8a316f67867761674/include/franka/robot.h#LL678C8-L678C30) method for that

**Comment by undefinedcodezhong** [comment]
Thank you, it helps!
