### ISSUE TITLE
How can i get the DH parameter to compute the Jacobian in null space？

### ISSUE THREAD

**Issue by wangjunhe8127** [frankaemika/libfranka#82]
How can i get the DH parameter to compute the Jacobian in null space？
in urdf？

**Comment by peasant98** [comment]
@wangjunhe8127, You can find the DH parameters of the robot [here](https://frankaemika.github.io/docs/control_parameters.html#denavithartenberg-parameters).

**Comment by AndreasKuhner** [comment]
Hi @wangjunhe8127 ,
I hope @peasant98 could answer your question, thanks!

If anything is still open, don't hesitate to throw it at us... :smile: 

Cheers,
Andreas
