### ISSUE TITLE
logging, csv: Should use `q_c` instead of second `q_d`?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [frankaemika/libfranka#87]
For the logging code here:
https://github.com/frankaemika/libfranka/blob/f1f46fb008a37eb0d1dba00c971ff7e5a7bfbfd3/src/logger.cpp#L31
which gets written to CSV here:
https://github.com/frankaemika/libfranka/blob/f1f46fb008a37eb0d1dba00c971ff7e5a7bfbfd3/src/log.cpp#L44-L45

It seems like `q_c` might've been better, because it would've allowed for unique headers.

When I load up this CSV file with `pandas`, I get columns like `q_d[3]` for `robot_state.q_d[3]` and `q_d[3].1` for `robot_command.joint_position[3]`.

Example notebook / plots and stuff:
https://github.com/EricCousineau-TRI/libfranka/blob/159876127a5a163dfa7fc4424a684b95f678bab3/tmp/plot_joints_libfranka.ipynb

**Comment by AndreasKuhner** [comment]
Hi @EricCousineau-TRI ,
thank you for the input. Will be considered for future feature :grinning: 

Cheers,
Andreas
