### ISSUE TITLE
How does cartesian control work under the hood?

### ISSUE THREAD

**Issue by peasant98** [frankaemika/libfranka#90]
Hi, I was curious how the Franka Panda generates joint trajectories from desired Cartesian poses.

I noticed  https://frankaemika.github.io/libfranka/generate_cartesian_pose_motion_8cpp-example.html, but it doesn't seem to show what's really happening under the hood.

Thanks!

**Comment by AndreasKuhner** [comment]
Hi @peasant98 ,
a quick answer would be that we run the IK under-the-hood and translate Cartesian motions into joint space.

Cheers,
Andreas
