### ISSUE TITLE
where is the gravity compensation term in impedance control

### ISSUE THREAD

**Issue by RanCao2018** [frankaemika/libfranka#98]
Hi, thank you for your work!
I have seen the cartesian impedance controller in ["cartesian_impedance_control.cpp".](https://github.com/frankaemika/libfranka/blob/f1f46fb008a37eb0d1dba00c971ff7e5a7bfbfd3/examples/cartesian_impedance_control.cpp) But I found the torque command only supplies a Coriolis torque compensation (at line 105).  So where is the gravity compensation term?

**Comment by peasant98** [comment]
I believe that it's taken care of under the hood.

**Comment by alisonjpp** [comment]
franka does the gravity compensation itself

**Comment by AndreasKuhner** [comment]
Hi @RanCao2018 ,
@alisonjpp perfectly answered it. 

For further input... the https://github.com/frankaemika/libfranka/blob/main/examples/communication_test.cpp example shows e.g. how to control the robot in 'gravity compensation mode' aka 'just send 0 torques to all joints'. Everything else is taken care of in the background.

Cheers,
Andreas
