### ISSUE TITLE
Freeze during Building Cmakefiles, Libfranka

### ISSUE THREAD

**Issue by palaniappanvr** [frankaemika/libfranka#99]
I am totally new to ROS, 
When I build the cmake files, the system freezes in the middle around 58 percent. Is there anyway to solve this?
I'm running Ubuntu on virtual desktop which I have set a RAM of 2 GB and a memory of 50gb. Is this supposed to be enough?

**Comment by AndreasKuhner** [comment]
Hi @palaniappanvr ,
2gb sounds a bit less (no matter what you want to compile). Often enough, if the system runs out of memory, it starts to use the 'swap' which is super slow compared to normal RAM - often enough leading to a system freeze and eventual reboot.

Nowadays, my experience is that between 16gb to 32gb is quite comfortable and allows one to build programs with more than a single core :smile: 

Cheers,
Andreas
